services:
  postgres:
    container_name: postgres
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: testpwd
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - 5432:5432